[package]
name = "vptree"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
rand = "0.8.5"
min-max-heap = "1.3.0"

[dev-dependencies]
criterion = { version = "0.3", features=['real_blackbox', 'html_reports'] }

[[bench]]
name = "bench"
harness = false
